name: Deploy to heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.12.14 # Deploy to heroku: https://github.com/marketplace/actions/deploy-to-heroku
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_EXCUTE}}
          heroku_app_name: "botchi-go" #Must be unique in Heroku
          heroku_email: "oys1751@gmail.com"
        env:
          HD_DISCORD_BOT_TOKEN: ${{secrets.DISCORD_BOT_TOKEN}}
